### ISSUE TITLE
Does suid work with solid start?

### ISSUE THREAD

**Issue by nxy7** [swordev/suid#139]
When running solid start with suid I either get
```
TypeError: suidPlugin is not a function
```
when trying to include it in vite build or
```
ReferenceError: document is not defined
```
if I use any suid component in the app. To reproduce use starter solid start template

```
pnpm create solid
```
and then add suid dependencies.

**Comment by atzzCokeK** [comment]
the same thing happens to me. I am not sure if it works.

**Comment by nxy7** [comment]
Weird thing is it somehow almost works without suidPlugin(). It throws errors, but if you ignore them a couple times suid elements are actually displayed on the page :P

**Comment by demoran23** [comment]
The typing on suidPlugin is incorrect.  You'll want to reference it as `suidPlugin.default()`.

**Comment by juanrgm** [comment]
With the latest version (https://github.com/swordev/suid/pull/143) you can use suid with solid-start, but you must disable the SSR.

```ts
// vite.config.ts
import suid from "@suid/vite-plugin";
import solid from "solid-start/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [suid(), solid({ ssr: false })],
});
```

**Comment by awojciak** [comment]
@juanrgm so, SUID still can't be used with SSR? when SSR-ready version could be released?

**Comment by ron-wade** [comment]
Thanks for this great library. I would also like to know if SSR compatibility is on the roadmap.

**Comment by juanrgm** [comment]
I am adding support to SSR, but it is being locked by this issue (https://github.com/solidjs/solid-start/issues/475).

**Comment by orenelbaum** [comment]
The fix was merged in v1.6.3

**Comment by orenelbaum** [comment]
It's good that you're finding the bugs, but I understand that it can be annoying.
I fixed the bug.
If you want to patch node_modules until it's merged you can go to `node_modules\solid-js\dist\server.cjs` and replace line 302
`const v = (sources[i] || {})[key];`
with
```
let s = (sources[i] || {});
if (typeof s === "function") s = s();
const v = s[key];
```
Generally I can try prioritizing bugs you encounter if that helps, as long as I have free time.

**Comment by orenelbaum** [comment]
Fix is live now

**Comment by damianesteban** [comment]
I get the following error with suid and soldstart:

https://d.pr/i/3z4vok/eFQbFxwJqR

After I refresh the page everything is cool.

**Comment by vivCoding** [comment]
I have the same issue as @damianesteban with `suid` and `solidstart` (setup described as OP), where I get `document is not defined`, and then goes away if I "clear errors and retry". The problem persists if I refresh page.

The only thing that seems to fix the issue is disabling SSR on `solid-start`, as mentioned earlier in this thread (not really ideal).

**Comment by damianesteban** [comment]
@vivCoding Thank you. Looks like I'll be using Tailwind for my project with SolidStart :)

**Comment by IS2511** [comment]
> With the latest version (#143) you can use suid with solid-start, but you must disable the SSR.

Is SSR support planned? Will SSR support ever be available for SUID? It really bothers me, `solid-start` supports SSR "out of the box" and an extension breaking it makes me sad.

**Comment by juanrgm** [comment]
I am working in it.

With [@suid/material@0.9.0](https://github.com/swordev/suid/releases/tag/%40suid%2Fmaterial%400.9.0) there is support partial support for SSR. For example, you can create styled components:

```ts
import { styled } from "@suid/material/styles";

const Div = styled('div')({ color: "red" });
```

But not all components are ready, this require review each component to adapt it to SSR.

**Comment by madaxen86** [comment]
I'll just leave my experience here.
1. What I wanted to achieve:
- Solid Start SSR
- Using media query "prefers-color-scheme:dark" to set the palette mode prop automatically
- fallback on server is "light"

2. What happens:
- first render: the server renders the page in light theme - so far so good.
- when the client prefers the dark mode the onMount will set the darkMode signal to true -> "dark"
So now comes the weird part.
The body now has a black background, the text is white for <p> tags.
The buttons and papers (SUID components) still have the light theme colors !?
Then I added console logs also in the  sx props and they say they use the dark theme but render the light theme !?

Then when I manually change the color scheme to light - light theme is applied correctly, when I switch to dark - dark theme is applied correctly.

Has anyone achieved SSR and using the  media query to update the theme on the client?

**Comment by rtritto** [comment]
There is a guide/template to use _suid_ with SSR?

Like [MUI Server rendering](https://mui.com/material-ui/guides/server-rendering), for the cache, should I use [Emotion Solid](https://github.com/tqwewe/emotion-solid) or _suid_ styled engine?

PS: I'm using _vite-plugin-ssr_

**Comment by franckdervaux** [comment]
When building a solid-start application with suid, not using SSR, I get the following error:
`Error [RollupError]: Could not resolve "./ThemeContext" from "node_modules/@suid/system/useTheme.js"`
I am using said version 0.15.1 with solid-start 0.3.6.

**Comment by hakatashi** [comment]
For people struggling using SUID with SolidStart **1.0**:

By following [getting started guide](https://suid.io/getting-started/installation), I got `SyntaxError: Unexpected token 'export'` error.

To resolve it, instead of adding `vite.config.ts` to your project, write `app.config.ts` like this:

```
import { defineConfig } from "@solidjs/start/config";
import suidPlugin from "@suid/vite-plugin";

export default defineConfig({
  vite: {
    plugins: [suidPlugin()],
    build: {
      target: "esnext",
    },
  },
});
```

SSR is apparently working fine.

**Comment by stevenlyd** [comment]
> For people struggling using SUID with SolidStart **1.0**:
> 
> By following [getting started guide](https://suid.io/getting-started/installation), I got `SyntaxError: Unexpected token 'export'` error.
> 
> To resolve it, instead of adding `vite.config.ts` to your project, write `app.config.ts` like this:
> 
> ```
> import { defineConfig } from "@solidjs/start/config";
> import suidPlugin from "@suid/vite-plugin";
> 
> export default defineConfig({
>   vite: {
>     plugins: [suidPlugin()],
>     build: {
>       target: "esnext",
>     },
>   },
> });
> ```
> 
> SSR is apparently working fine.

This works, thank you!
